a=int(input("Enter a number: "))
print("\t---------------------------")
print("\tMultiplication Table of",a)
print("\t---------------------------")
print("\t",a,"x 1 =",a*1)
print("\t",a,"x 2 =",a*2)
print("\t",a,"x 3 =",a*3)
print("\t",a,"x 4 =",a*4)
print("\t",a,"x 5 =",a*5)
print("\t",a,"x 6 =",a*6)
print("\t",a,"x 7 =",a*7)
print("\t",a,"x 8 =",a*8)
print("\t",a,"x 9 =",a*9)
print("\t",a,"x 10 =",a*10)
